### ISSUE TITLE
component events don't fire

### ISSUE THREAD

**Issue by optikalefx** [runspired/ember-gestures#16]
Currently using fastclick with no issues. When I switched to ember-gestures, any components that have an event defined, as in:

``` javascript
export default Component.extend({
   click() { /.../ }
});
```

don't fire.  Double checking with a CSS outline shows I definitely have area to tap on. I tried `click` and `touchend` both don't fire. The rest of buttons and a tags do fire.

This is tested on iOS 9, iPhone 6 mobile safari, debugged using desktop safari on mac. Confirmed on 2 different components.

**Comment by runspired** [comment]
@optikalefx I need to expand the docs apparently :P 

This section specifically, if you have a moment: https://github.com/runspired/ember-gestures#using-touch-action-as-a-fastclick

Your component need to bind the style attribute listed there to the string used in the example.

```js
import Ember from 'ember';

const {
  Component
} = Ember;

const {
  SafeString
} = Ember.Handlebars;

export default Component.extend({
   click() { /.../ },

   attributeBindings: ['style', 'disabled', 'type'],
   style: new SafeString('touch-action: manipulation; -ms-touch-action: manipulation;')

});
```

**Comment by runspired** [comment]
Added to docs: https://github.com/runspired/ember-gestures/commit/ad6997072b879543e09e5c9943fb709a2ed8681f

**Comment by optikalefx** [comment]
That's super lame isn't it? At a minimum I think you should ship a mixin that can be used in a component. I mean every single component in a mobile app that has an event will need this?

**Comment by runspired** [comment]
@optikalefx ime / imo using `click` on a component is an antipattern.  I considered reopening `component` to add this automatically if `click` is present (you can still do that), but tbh just using an AST Walker on a Glimmer component is probably the cleanest path forward, we just have to wait for glimmer components to land.  Automatically adding things to `attributeBindings` is prone to conflicts.

If you want to reopen, do this.
```
Ember.Component.reopenClass({
  attributeBindings: ['touchActionStyle:style'],
  touchActionStyle: computed(function() {
    return new Ember.Handlebars.SafeString( this.click ? 'touch-action: manipulation; -ms-touch-action: manipulation;' : '' );
  })
});
```

**Comment by optikalefx** [comment]
I'm curious to hear what a better pattern for this setup is. The premise is that this component is a _back button_. inside of a header component. There are 5 header components that different, and they all use this back button component.

That back button component handles figuring out what page to go back to, IMO a great place to handle back functionality.

If the click is not inside the component, this work would have to be an action on all 5 inclusions of the component and passed the action from something higher up. A much more convoluted setup I think.

**Comment by runspired** [comment]
@optikalefx that's a complex question with a complicated answer. 

Some of the answer is the complexity of jQuery eventing: https://ember-twiddle.com/847601d7383bc60052b4

Some of the answer is the performance hit that you take when you use jQuery eventing, and the second hit you take when you use Ember's event delegation on top of that.

There is currently no good answer to this question, so for now, sticking with `click` is the way to go.  Now that ember-gestures is almost to 0.1 and Hammer 2.0.5 is out, I can focus back on finishing https://github.com/runspired/ember-capture-eventing, which contains one possible good answer to this question.

**Comment by runspired** [comment]
@optikalefx the RFC for which the ember-capture-eventing addon is an experimental playground: https://github.com/emberjs/rfcs/pull/86

**Comment by runspired** [comment]
@optikalefx after thinking about this a little bit more, I think I'm going to do the `reopen` in `0.0.9`, I'll push it up tomorrow morning.

**Comment by optikalefx** [comment]
Alright, I think at least for now, it's the most expected. Maybe most people don't have components that act on themselves like this, but I think it's useful when it comes up

**Comment by optikalefx** [comment]
let's keep this open until 0.0.9 is out with that update

**Comment by runspired** [comment]
0.0.9 is staged and ready, but I'm also locking it to Hammer 2.0.6 which is coming shortly.
