### ISSUE TITLE
scrolling initiated on component with pan recognizers doesn't work

### ISSUE THREAD

**Issue by kbullaughey** [runspired/ember-gestures#32]
When I enable the pan recognizer on a component, an attempt to scroll the page where the touch gesture starts on the component doesn't result in the page scrolling. I need to begin the touch somewhere else to scroll. When I remove `pan` from the list of recognizers, scrolling works as expected.

The README has a comment about how `pan` is horizontal-only so it doesn't break scrolling, is this related? I would have thought scrolling should work.

**Comment by runspired** [comment]
It ought to work with `pan`, yes.  Check that you have Hammer 2.0.6, if you do, we have a config issue we need to fix.

**Comment by runspired** [comment]
(or, we accidentally introduced a bug in Hammer, either way, need to fix)

**Comment by kbullaughey** [comment]
Yes, I do have Hammer 2.0.6.

**Comment by Jordan4jc** [comment]
I'm now having this problem too, exact same setup (minus tap)

**Comment by martinciu** [comment]
I have the same issue with `swipe` gesture. I want to use `swipeRight` and swipeUp/Down should to the scrolling.

**Comment by dantistus** [comment]
I have same issue with pinch recognizer...
