### ISSUE TITLE
Installation from master fails to run

### ISSUE THREAD

**Issue by optikalefx** [runspired/ember-gestures#39]
Uncaught Error: Could not find module `ember-getowner-polyfill` imported from `factsumo/instance-initializers/ember-gestures

**Comment by olivierlesnicki** [comment]
+1

**Comment by jhr007** [comment]
Install the polyfill... 
`ember install ember-getowner-polyfill`

`Ember.getOwner` was added in 2.2? 2.3? 2.4? versions.

**Comment by optikalefx** [comment]
The plugin should have a dependency on an ember version or include the polyfill if it's not.

**Comment by olivierlesnicki** [comment]
Agree with @optikalefx

**Comment by olivierlesnicki** [comment]
While the solution is obvious, this should be added by default by the library or at least a warning should be thrown.

**Comment by jhr007** [comment]
In PR  #44 , I moved it from `devDependencies` to  `dependencies`...

**Comment by djsegal** [comment]
Can this update be put into a new version on ember observer?
