### ISSUE TITLE
support for top-level DOM tap events not inside component?

### ISSUE THREAD

**Issue by kbullaughey** [runspired/ember-gestures#40]
Is there a way to respond to gestures in top-level templates? i.e., not from within a component. I used to do the following:

    Ember.View.extend(RecognizerMixin, {
      recognizers: ['tap'],
      tap(event) {
        // do something requiring event here
      }
    });

But now that views are gone this seems not to be an option. For regular click events, we can trigger an event, and get access to the event object, by attaching a DOM event handler using `{{action}}`:

    <div onclick={{action "doSomething"}}>
      ...
    </div>
    
But my impression is that this only works for clicks, not taps. And if we use this format:

    <div {{action "doSomething" on="tap"}}>
      ...
    </div>

Then we don't get the event object.

My work-around was to make a component that mixes in `RecognizerMixin` and wraps my whole template. Is this the only option? Does it have any drawbacks? 

Is the `ontap={{action "doSomething"}}` syntax something we aim to support? If so, I'm not sure where to start thinking about what would need to be done, give we no longer will have Ember.View.

**Comment by runspired** [comment]
>  Is the ontap={{action "doSomething"}} syntax something we aim to support?

No.

> Then we don't get the event object.

I think it's something like `target="target"` to get the event.

> I used to do the following:

You can use the legacy views addon, or wrap the top level in a component as you did.  Unfortunately, this won't get any easier until routable-components lands.

**Comment by kbullaughey** [comment]
I think it makes sense to wait for routable components, given there are workarounds. Closing.
