### ISSUE TITLE
double-tap and single-tap recognizers missing in host app

### ISSUE THREAD

**Issue by simonihmig** [runspired/ember-gestures#41]
Are those two recognizers intentionally not injected into the consuming host app? All other recognizers have a "link" in the app/ember-gestures/recognizers/ folder to the corresponding source file in the addon folder, but not those two!?

**Comment by runspired** [comment]
This is intentional, they are non-standard recognizers implemented merely as a demo.  To install them, run the blueprint `ember g doubletap-recognizer`

**Comment by simonihmig** [comment]
I see, thanks for clarification!
