### ISSUE TITLE
How to prevent ghost clicks

### ISSUE THREAD

**Issue by simonihmig** [runspired/ember-gestures#45]
Is there any recommended way on how to prevent ghost clicks when using a tap recognizer? 

Should I just include the fix suggested here: http://hammerjs.github.io/tips/? Or is there any other preferred mechanism in the context of ember-gestures?

**Comment by runspired** [comment]
Don't use tap as a replacement for click, use click, this is why the hammer-time polyfill (made available by ember-hammertime) is important.

**Comment by nicwillemse** [comment]
I have not been able to overcome this - I think it would be good to add a solution to the documentation ?

**Comment by eriktrom** [comment]
@nicwillemse - trying installing the latest release which includes updated version of `ember-hammertime` - if u still see issues, come back and report them.

(release published 30 min ago, fresh off the press)
