### ISSUE TITLE
hammer.js is outdated though installed from runspired/hammer.js#develop

### ISSUE THREAD

**Issue by simonihmig** [runspired/ember-gestures#5]
The docs say one should install hammer.js from the forked repo by using `bower install --save runspired/hammer.js#develop`.
However that repository contains some changes in the src files, but there seems to be no freshly built hammer.js file in there, see the comparison: https://github.com/hammerjs/hammer.js/compare/master...runspired:develop

So the file installed by bower won't contain any of those changes!

**Comment by runspired** [comment]
doh :'(

Hammer 2.0.5 lands sometime this week though :)  PR is in, waiting final release approval.

**Comment by runspired** [comment]
Addressed with release of Hammer 2.0.5 and ember-gestures 0.0.8
