### ISSUE TITLE
Gesture events not available in components?

### ISSUE THREAD

**Issue by simonihmig** [runspired/ember-gestures#6]
Is this example from the Readme supposed to actually work?

```js
import Ember from 'ember';

const {
  Component
} = Ember;

export default Component.extend({
  panStart(e) {
     ... do something with the event ...
    }
});
```

I could not get this to work. However using the RecognizersMixin in our components seems to make this work. However this ist not documented anywhere!?

**Comment by runspired** [comment]
yes, you must use a recognizer somewhere within the DOM tree where you'd like to be able to handle the events, there is no global recognizer as having one would break your ability to scroll or use other native functionality when desired.
