### ISSUE TITLE
ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `touch-action`

### ISSUE THREAD

**Issue by xtagon** [runspired/ember-gestures#65]
Hi,

Every since starting to use Ember-Gestures (which is fantastic, BTW!) I have the following deprecation warnings in my logs:

> DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `touch-action`.
> DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `touch-action`.

Any idea how this can be fixed?

Thanks,
Justin

**Comment by runspired** [comment]
Update ember-hammertime

**Comment by xtagon** [comment]
Thanks, that worked. I wonder why `ember install ember-gestures` installed a much older version.
