### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by frederikbosch** [runspired/ember-gestures#7]
This project is really in need for documentation, I am [an addon writer myself](https://github.com/genkgo/ember-localforage-adapter) but I am not able to get this running decently.

The steps I took to try too get this working.

1. Add config
```js
# config/environment.js
ENV.gestures = {
    //passed to the respective recognizer
    tune: {
      tap: {time: 250, threshold: 9}, //Hammer default is 250 / 2
      press: {time: 500, threshold: 9}, //Hammer default is 500 / 5
      swipe: {direction: 7, velocity: 0.5, threshold: 9},
      pan: {direction: 6},
      pinch: {},
      rotate: {}
    }
  };
```

2. Create recognizer
```sh
ember g recognizer swipe
```

3.  Create the template based on included component
```hbs
{{#context-element
    on-swipeleft="toggleNav"
    on-swiperight="closeNav"
}}
... my yielded content....
{{/context-element}}
```

This is not working. What am I doing wrong? I also do not see any `style="touch-action: <foo>;"` appearing. Maybe the result of this thread can result in basic documentation how to get this addon working.

**Comment by runspired** [comment]
@frederikbosch ping me on slack, the lack of docs is in fact intentional atm (same reason this hasn't gone to even it's first minor).  For ember-gestures to really work you must use a fixed version of Hammer, which doesn't exist yet.  We (the Hammer team) are still patching known bugs for the 2.0.5 release which this is going to depend on.

**Comment by frederikbosch** [comment]
@runspired Can you point me to the specific bugs for Hammer 2.0.5? Maybe I can help to fix one the bugs.

**Comment by frederikbosch** [comment]
@runspired I created an hammer.js issue for the list of blockers.

**Comment by frederikbosch** [comment]
@runspired Just found out that you really invested in the project. Awesome work! Really, thanks for all the effort!
